# Generated by Django 4.1.5 on 2023-07-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionMeta",
            fields=[
                (
                    "question_meta_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("answer_variants", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_ids", models.CharField(max_length=64)),
                ("honeypot_indexes", models.CharField(max_length=64)),
                (
                    "question_meta_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.questionmeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerAssignment",
            fields=[
                (
                    "worker_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("room_id", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("nw", "new"),
                            ("pd", "pending"),
                            ("as", "assigned"),
                            ("fl", "failed"),
                            ("dn", "done"),
                        ],
                        default="nw",
                        max_length=2,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("login", models.CharField(max_length=25, null=True, unique=True)),
                ("assignment_id", models.CharField(max_length=96, null=True)),
                ("turk_submit_to", models.CharField(max_length=40, null=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.avatar",
                    ),
                ),
                (
                    "mood",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.mood",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_set_progress", models.IntegerField(default=0)),
                ("last_activity_time", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("finished", models.BooleanField(default=False)),
                (
                    "question_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.questionset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.CharField(max_length=1024)),
                (
                    "question_image",
                    models.CharField(default="", max_length=1024, null=True),
                ),
                ("correct_answer", models.IntegerField()),
                (
                    "question_meta_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.questionmeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.workerassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(default="{}", max_length=128)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "question")},
            },
        ),
    ]
