# Generated by Django 4.1.5 on 2023-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_questionanswerstate_createion_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerassignment",
            name="quit_level",
            field=models.IntegerField(default=-1),
        ),
    ]
