# Generated by Django 4.1.5 on 2023-10-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_workerassignment_quit_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("vote", "vote"), ("submit", "submit")], max_length=8
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.CharField(max_length=96)),
            ],
        ),
        migrations.AlterField(
            model_name="questionanswerstate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
