# Generated by Django 4.1.5 on 2023-10-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_actionrecord_alter_questionanswerstate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionrecord",
            name="worker",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.workerassignment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actionrecord",
            name="action_type",
            field=models.CharField(choices=[("vote", "vote")], max_length=8),
        ),
    ]
