# Generated by Django 4.1.5 on 2023-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_actionrecord_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerassignment",
            name="survey_code",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
