# Generated by Django 5.0.6 on 2024-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_workerassignment_survey_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bonus_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerassignment',
            name='bonus_score',
            field=models.IntegerField(default=0),
        ),
    ]
