# Generated by Django 5.0.6 on 2024-11-10 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_room_bonus_score_workerassignment_bonus_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='createion_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='action_type',
            field=models.CharField(choices=[('vote', 'vote'), ('lend', 'lend'), ('atran', 'atran'), ('action', 'action')], max_length=8),
        ),
    ]
