# Generated by Django 5.0.6 on 2025-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_questionset_createion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
    ]
