# Generated by Django 5.0.6 on 2025-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_questionset_level_questionset_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerassignment',
            name='missed_questions',
            field=models.IntegerField(default=0),
        ),
    ]
