# Generated by Django 5.0.6 on 2025-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_workerassignment_missed_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerassignment',
            name='quit_reason',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
