upstream collabel_django {
    server app:8000;
}

upstream collabel_ws {
    server app:8001;
}

server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl reuseport;
    listen [::]:443 ssl reuseport;

    # Domain names this server should respond to.
    server_name www.collaborativegames.net;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/test-name/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/test-name/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location /static/ {
        alias /collabel/static/;
    }

    location /ws {
        proxy_pass http://collabel_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://collabel_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header "X-Frame-Options" "Allow-From mturk.com";
        add_header Content-Security-Policy "frame-ancestors *.mturk.com";
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
